### ISSUE TITLE
Why switch from HTTPX to Requests?

### ISSUE THREAD

**Issue by sethmlarson** [PendragonLore/anido#1]
Hey @PendragonLore! :wave: 

Dropping in to ask you if there was any specific reason you switched from HTTPX to Requests?

I'm one of the maintainers of HTTPX and if you switched due to a problem or missing feature we'd love to hear about it. :)

Thanks for your time!

**Comment by PendragonLore** [comment]
Hello.

I switched from HTTPX to Requests due to some issues I ran into.

* Streaming breaks when bundled with PyInstaller, here's a [dump of the stack trace](https://mystb.in/cipiparicu.py), this is the main reason why.
* Not being able to choose the size of the chunks from `Request.stream()`.
* Lack of a context manager to close a request on ``__exit__``.

I am still relatively new to the HTTPX API, so it would be great if you could correct me.

Thanks.

**Comment by sethmlarson** [comment]
This is great information, thank you for sharing the issues you've found with HTTPX, especially when using from PyInstaller!

I'm tracking the issues you've mentioned here:
- [hstspreload not available within PyInstaller](https://github.com/python-http/hstspreload/issues/2)
- [Allow setting chunk_size for Response.stream() and Response.stream_text()](https://github.com/encode/httpx/issues/394)
- [Allow Responses to be used as Context Managers](https://github.com/encode/httpx/issues/393)

Feel free to reach out to us or create issues on our issue tracker if you decide to try HTTPX again in the future. :bowing_man:

**Comment by PendragonLore** [comment]
Thanks for the quick response and for tracking the issues, I will definetly look into using HTTPX in the future.

I consider this closed for now, hope you have a good day!
